FROM python:3.7-slim

RUN mkdir -p /app \
    && apt update \
    && apt install -y --no-install-recommends \
       build-essential \
       git \
       libasound-dev \
       libportaudio2 \
       libportaudiocpp0 \
       portaudio19-dev \
       libsndfile1-dev \
       libffi-dev \
       unzip \
       wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

COPY requirements.txt .

RUN pip install -U pip \
    && pip install -r requirements.txt \
    && git clone -b v0.3.32 https://github.com/alphacep/vosk-api.git \
    && cd vosk-api/python/example \
    && wget https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip \
    && unzip vosk-model-small-en-us-0.15.zip \
    && mv vosk-model-small-en-us-0.15 model \
    && rm vosk-model-small-en-us-0.15.zip


WORKDIR /app/vosk-api/python/example

CMD ["python", "test_microphone.py"]


